### PR TITLE
Pills 2-4: edit for style and clarity

### PR DESCRIPTION
**Pull request by michaelpj**
More in the vein of https://github.com/NixOS/nix-pills/pull/25.

### CODE REVIEW

**Comment by grahamc** [comment]
@disassembler can you review this diff?

**Comment by grahamc** [comment]
FWIW these are really hard to review, because of how long they are. I'm trying to sit down and dedicate the time to review it.

**Comment by michaelpj** [comment]
I'm open to suggestions - the problem is that there's just a lot of text in these docs and going through it is going to involve a lot of changes...

**Comment by grahamc** [comment]
Ok @michaelpj I've decided to just accept your changes. You're doing great work, and I don't need to be a gatekeeper here for you.

**Comment by grahamc** [comment]
Thank you a lot, sorry for the long delay. The next one will be much faster!

**Pull request merged**
