### PR TITLE
Update GNU Hello version to 2.10

### PR DESCRIPTION
**Pull request by lezed1**
I was just going through the pills and found the GNU Hello version was one behind. This PR updates pill 8 to use the latest GNU Hello.

### CODE REVIEW

**Comment by lezed1** [comment]
I think the only reference to GNU Hello is in this linked Gist: https://gist.github.com/lethalman/97fae227329b442267bc

**Comment by grahamc** [comment]
Hey nice, before I accept this PR though I need to give you the opportunity to rescind it. The Nix Pills were licensed CC-BY-SA-4.0 since you put this PR in. Before, it had no license. Are you OK with contributing to the project under that license? Usually I wouldn't have to ask, but the license didn't exist when you put this PR in :)

**Comment by lezed1** [comment]
What timing! Having the PR under that license is fine, thanks for asking.

**Comment by grahamc** [comment]
Thanks!

**Pull request merged**
